---
# Kevin M. Meziere <kmeziere@jpcatholic.com>
# Copyright 2015, John Paul the Great Catholic University

- name: Lookup version of Sniffle
  shell: pkgin list | grep fifo-sniffle | awk '{print $1}'
  register: sniffle_version_installed
  changed_when: sniffle_version_installed.stdout != '{{sniffle_version_required}}'
  ignore_errors: True

- name: Install/Upgrade Sniffle
  command: pkg_add -u http://release.project-fifo.net/pkg/'{{sniffle_release}}'/'{{sniffle_version_required}}'.tgz 
  when: sniffle_version_installed.stdout != '{{sniffle_version_required}}'

- name: Configure Sniffle
  template: src=sniffle-config.j2 dest=/opt/local/fifo-sniffle/etc/sniffle.conf backup=yes
  notify: Bounce Sniffle

- name: Enable Sniffle
  service: name=sniffle state=started enabled=yes
  when: "'sniffle_no_start' not in group_names"