---
# Kevin M. Meziere <kmeziere@jpcatholic.com>
# Copyright 2015, John Paul the Great Catholic University

- name: Lookup version of Sniffle
  shell: "pkgin list | grep fifo-sniffle | awk '{print $1}'"
  register: sniffle_version_installed
  changed_when: "sniffle_version_installed.stdout != '{{ sniffle_version_required }}'"
  ignore_errors: True

- name: Check for Project Fifo GPG Key
  shell: "gpg --keyring /opt/local/etc/gnupg/pkgsrc.gpg --fingerprint | grep '{{ fifo_gpg_keyid }}'"
  register: fifo_gpg_key
  changed_when: fifo_gpg_key.rc != 0
  ignore_errors: True
  when: sniffle_version_installed.stdout != "{{ sniffle_version_required }}"

- name: Install Project Fifo GPG Key
  shell: "curl https://project-fifo.net/fifo.gpg | gpg --primary-keyring /opt/local/etc/gnupg/pkgsrc.gpg --import"
  when: fifo_gpg_key.rc != 0

- name: Install/Upgrade Sniffle
  command: "pkg_add -u http://release.project-fifo.net/pkg/'{{ sniffle_release }}'/'{{ sniffle_version_required }}'.tgz"
  when: sniffle_version_installed.stdout != "{{ sniffle_version_required }}"

- name: Configure Sniffle
  template: src=sniffle-config.j2 dest=/opt/local/fifo-sniffle/etc/sniffle.conf backup=yes
  notify: Bounce Sniffle

- name: Enable EPMD
  service: name=epmd state=started enabled=yes
  when: "'sniffle_no_start' not in {{ group_names }}"

- name: Enable Sniffle
  service: name=sniffle state=started enabled=yes
  when: "'sniffle_no_start' not in {{ group_names }}"
  register: sniffle_service_start

- name: Pause for Sniffle Startup
  pause: seconds=20
  when: sniffle_service_start.changed != False